networks:
  mynet:

volumes:
  db-vol:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - mynet
  myapp:
    image: stackupiss/northwind-app:v1
    networks:
      - mynet
    ports:
      - 8000-9000:3000
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
