---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  namespace: myns
  labels:
    app: dov
type: Opaque
data:
  INSTANCE_NAME: dGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHN0cmluZw==
  DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deployment
  namespace: myns # if not specified, goes to default. remove to use -n to specify namespace
  labels:
    app: dov
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov
  template:
    metadata:
      name: dov-po
      labels:
        app: dov
        dept: eng
    spec:
      containers:
        - name: dov-container
          image: kraftedcheese/dov-bear:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTANCE_NAME
              value: "k8s dov bear"
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - secretRef:
                name: dov-secret
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
spec:
  type: ClusterIP
  selector:
    app: dov
    dept: eng
  ports:
    - port: 8000
      targetPort: 5000
---

