---
apiVersion: v1
kind: Pod
metadata:
  name: dov-po
  namespace: myns
  labels:
    app: dov
    dept: eng
spec:
  containers:
    - name: dov-container
      image: kraftedcheese/dov-bear:v1.0.0
      imagePullPolicy:
      env:
        - name: INSTANCE_NAME
          value: "k8s dov bear"
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 3000
