apiVersion: v1
kind: Namespace
metadata:
  name: codeserver
  labels:
    name: codeserver
---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-configmap
  namespace: codeserver
data:
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-144.126.243.173.nip.io
  TZ: Asia/Singapore
