apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  namespace: bggns
  labels:
    app: bggapp
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-configmap
  namespace: bggns
  labels:
    app: bggapp
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
