apiVersion: v1
kind: Namespace
metadata:
  name: minions
  labels:
    name: minions
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
type: Opaque
data:
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
  MINIO_ROOT_USER: dXNlcg==
