apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minions
  labels:
    app: minio
    name: minio-sts
spec:
  serviceName: minio-hsvc
  replicas: 3
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
    - metadata:
        name: minio-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      initContainers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "chown 1001:1001 /data"
          volumeMounts:
            - name: minio-vol
              mountPath: /data
      containers:
        - name: minio-container
          image: bitnami/minio:2023.10.25
          imagePullPolicy: IfNotPresent
          command:
            - minio
            - server
            - --address=:9000
            - --console-address=:9090
            - http://minio-sts-{0...2}.minio-hsvc-minio-ns.svc.cluster.local/data
          envFrom:
            - secretRef:
                name: minio-secret
          # resources:
          #   limits:
          #     memory: "250Mi"
          #     cpu: "200m"
          ports:
            - containerPort: 9000
              name: minio-data
            - containerPort: 9090
              name: minio-console
          volumeMounts:
            - name: minio-vol
              mountPath: /data
          # livenessProbe:
          #   httpGet:
          #     path: /minio/health/live
          #     port: 9000
          #   periodSeconds: 60
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /minio/health/ready
          #     port: 9000
          #   periodSeconds: 60
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minions
  labels:
    app: minio
    name: minio-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: data-144.126.243.173.nip.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio-svc
                port:
                  name: minio-data
    - host: console-144.126.243.173.nip.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio-svc
                port:
                  name: minio-console
---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minions
  labels:
    app: minio
    name: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
    - name: minio-data
      port: 9000
      targetPort: 9000
    - name: minio-console
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minions
  labels:
    app: minio
    name: minio-svc
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
    - name: minio-data
      port: 9000
      targetPort: 9000
    - name: minio-console
      port: 9090
      targetPort: 9090
